---
title: "Personalized Schedules for Prostate Cancer"
author: "Dimitris Rizopoulos"
date: "Netherlands Cancer Institute<br/> January 23, 2020"
output:
  ioslides_presentation:
    css: pres.css
    widescreen: yes
    mathjax: default
    logo: emc.png
transition: none
runtime: shiny
---

<script type="text/x-mathjax-config">
  MathJax.Hub.Config({ TeX: { extensions: ["color.js"] }});
</script>

```{r setup, echo = FALSE, message = FALSE, warning = FALSE}
library("ggplot2")
library("JM")
load("./plotJM_data.RData")
```

# Background & Motivation

## Prostate Cancer (PC)

- PC is the 2nd most frequently diagnosed cancer in males worldwide
    + the most frequent in economically developed countries
    
<br/>

- Many countries run population screening programs using PSA blood tests
    + to identify men who have developed the disease
    + or men who have high risk of developing it
    
<br/>

- <font color = "red">However, these programs have resulted to high rates of 
over-diagnosis and overtreatment</font>
    + standard treatments have serious side-effects

## Prostate Cancer Active Surveillance
- To avoid over-treatment, men with low grade prostate cancer are advised active surveillance

<br/>

- <span style="color:red">Cancer progression</span> is tracked via:
    - Prostate-specific antigen measurements
    - Digital rectal examination
    - MRI
    - <span style="color:red">Biopsies</span>

## Prostate Cancer Active Surveillance (cont'd)

- Treatment is advised when cancer progression is observed
    - typically via biopsies when Gleason Score $\geq 7$

<br/>

<div style="float:center;text-align:center;width:50%;border:3px solid black">
<br/><br/>
<strong><font size="6" color = "red">Frequency of Biopsies</font></strong>
<br/><br/>
</div>

## Prostate Cancer Active Surveillance (cont'd)

- Two dimensions
  + <strong><font color = "red">Frequency</font></strong> of biopsies
  + <strong><font color = "red">Delay</font></strong> in finding progression
  
<br/>

- <strong><font color = "red">Delay</font></strong>: We want to find progression asap
  + typically delay $\leq 12-18$ months
  

<br/>

- <strong><font color = "red">Frequency</font></strong>: Biopsies have high burden
  + painful, cause complications, expensive

## Biopsies Schedules

- Different AS programs

<br/>

- Annual Biopsies
  + focus on minimizing delay
  + many <span style="color:red">unnecessary</span> biopsies for patients who progress slow

## Biopsies Schedules (cont'd)

- Less Frequent Biopsies - PRIAS
  + every 3 years or
  + annually if PSA doubling time < 10 (try to find faster progressions)


***

<br/> 
<br/> 

<div align = "center">
<font color = "black" size = "6">**Thank you for your attention!**</font>
</div>
<br/>
<div align = "center">
[http://www.drizopoulos.com/](http://www.drizopoulos.com/)
</div>

<br/> 
<br/>
<br/>

<div align = "center">
<font color = "black" size = "5">**These slides are available at:**</font>
</div>
<div align = "center">
<div align = "center">
[https://drizopoulos.github.io/cvGEE_presentations/](https://drizopoulos.github.io/cvGEE_presentations/)
</div>

